# Site settings
title: kimyongin
email: kimyongin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "한정된 목적은 인생을 간결하게 한다"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "http://kimyongin.github.io" # the base hostname & protocol for your site
github_username:  kimyongin

# Build settings
markdown: kramdown
#kramdown:
#input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)